services:
  resource-service:
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
      - GEMINI_API_KEY=${GEMINI_API_KEY}  # Pass through from host environment
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"

  data-producer:
    build:
      context: ./data-producer
    profiles: ["development"]
    environment:
      - API_URL=http://resource-service:8080/resources
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    depends_on:
      rabbitmq:
        condition: service_healthy
      resource-service:
        condition: service_healthy
    networks:
      - resource-network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: resource-rabbitmq
    ports:
      - "5672:5672"
      - "15674:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - resource-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 6s
      timeout: 5s
      retries: 5
      start_period: 6s
    restart: on-failure
